apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
     argocd-image-updater.argoproj.io/image-list: app=662930028566.dkr.ecr.us-east-1.amazonaws.com/ourrepo
     argocd-image-updater.argoproj.io/app.update-strategy: newest-build
     argocd-image-updater.argoproj.io/app.allow-tags: regexp:.*
     argocd-image-updater.argoproj.io/app.registry-secret: argocd-image-updater-ecr
     argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
     argocd-image-updater.argoproj.io/app.helm.image-name: app.image.repository
     argocd-image-updater.argoproj.io/app.helm.image-tag: app.image.tag





spec:
  project: default
  source:
    repoURL: 'https://github.com/bassemosama/graduationproject_iti.git'
    targetRevision: HEAD
    path: 'helm-chart'
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
